# tools/sync_agent_assets.py
# Where: repository tooling for AI-agent assets.
# What: Generates native instruction, command, and skill adapters from shared sources.
# Why: Keep Codex, Cursor, Claude Code, GitHub Copilot, and Gemini aligned without hand-copying.

from __future__ import annotations

import argparse
import json
from pathlib import Path
import tomllib


GENERATED_NOTE = (
    "Generated by sync_agent_assets.py. Edit the shared source instead."
)
GENERATED_DYNAMIC_GLOBS = (
    ".claude/commands/*.md",
    ".cursor/commands/*.md",
    ".github/prompts/*.prompt.md",
    ".gemini/commands/*.toml",
    ".claude/skills/*/SKILL.md",
)
GENERATED_DYNAMIC_ROOTS = (
    ".claude/commands",
    ".cursor/commands",
    ".github/prompts",
    ".gemini/commands",
    ".claude/skills",
)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _to_bytes(text: str) -> bytes:
    return text.encode("utf-8")


def _strip_leading_html_comment(text: str) -> str:
    stripped = text.lstrip()
    if not stripped.startswith("<!--"):
        return text.strip() + "\n"
    end = stripped.find("-->")
    if end == -1:
        return text.strip() + "\n"
    return stripped[end + 3 :].lstrip().rstrip() + "\n"


def _markdown_header(path: str, what: str, why: str) -> str:
    return (
        "<!--\n"
        f"{path}\n"
        "Where: generated agent adapter.\n"
        f"What: {what}\n"
        f"Why: {why}\n"
        f"{GENERATED_NOTE}\n"
        "-->\n\n"
    )


def _toml_basic_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return f'"""\n{escaped.rstrip()}\n"""'


def _resolve_instruction_root(source_root: Path, output_root: Path) -> Path:
    if (output_root / "AGENTS.md").exists():
        return output_root
    return source_root


def _resolve_mcp_root(source_root: Path, output_root: Path) -> Path:
    if (output_root / ".mcp.json").exists():
        return output_root
    return source_root


def _agent_instruction_adapters(source_root: Path, output_root: Path) -> dict[Path, bytes]:
    instruction_root = _resolve_instruction_root(source_root, output_root)
    body = _strip_leading_html_comment(_read_text(instruction_root / "AGENTS.md"))
    return {
        output_root / "CLAUDE.md": _to_bytes(
            _markdown_header(
                "CLAUDE.md",
                "Claude Code project memory mirrored from AGENTS.md.",
                "Claude Code reads CLAUDE.md as project memory.",
            )
            + body
        ),
        output_root / "GEMINI.md": _to_bytes(
            _markdown_header(
                "GEMINI.md",
                "Gemini CLI project context mirrored from AGENTS.md.",
                "Gemini CLI reads GEMINI.md as hierarchical memory.",
            )
            + body
        ),
        output_root / ".github" / "copilot-instructions.md": _to_bytes(
            _markdown_header(
                ".github/copilot-instructions.md",
                "GitHub Copilot repository instructions mirrored from AGENTS.md.",
                "Copilot reads this file as repository-wide custom instructions.",
            )
            + body
        ),
        output_root / ".cursor" / "rules" / "project-guidelines.mdc": _to_bytes(
            "---\n"
            "description: Shared project instructions mirrored from AGENTS.md.\n"
            "globs:\n"
            "alwaysApply: true\n"
            "---\n\n"
            + _markdown_header(
                ".cursor/rules/project-guidelines.mdc",
                "Cursor project rule mirrored from AGENTS.md.",
                "Cursor reads .cursor/rules/*.mdc as reusable project rules.",
            )
            + body
        ),
    }


def _command_body(source: Path) -> str:
    return _strip_leading_html_comment(_read_text(source))


def _command_adapters(source_root: Path, output_root: Path) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    source_dir = source_root / ".agents" / "commands"
    for source in sorted(source_dir.glob("*.md")):
        name = source.stem
        body = _command_body(source)
        description = f"Shared repository command: {name}"

        outputs[output_root / ".claude" / "commands" / f"{name}.md"] = _to_bytes(
            _markdown_header(
                f".claude/commands/{name}.md",
                f"Claude Code command adapter for .agents/commands/{name}.md.",
                "Claude Code discovers project slash commands in .claude/commands.",
            )
            + body
            + "\nUser arguments from Claude Code, if any:\n$ARGUMENTS\n"
        )
        outputs[output_root / ".cursor" / "commands" / f"{name}.md"] = _to_bytes(
            _markdown_header(
                f".cursor/commands/{name}.md",
                f"Cursor command adapter for .agents/commands/{name}.md.",
                "Cursor discovers project commands in .cursor/commands.",
            )
            + body
            + "\nIf text is provided after the command name, treat it as the command scope.\n"
        )
        outputs[output_root / ".github" / "prompts" / f"{name}.prompt.md"] = _to_bytes(
            _markdown_header(
                f".github/prompts/{name}.prompt.md",
                f"GitHub Copilot prompt adapter for .agents/commands/{name}.md.",
                "Copilot discovers reusable prompt files in .github/prompts.",
            )
            + body
            + "\nUse selected files, chat context, and any prompt arguments as scope.\n"
        )
        gemini_prompt = body + "\nUser arguments from Gemini CLI, if any:\n{{args}}\n"
        outputs[output_root / ".gemini" / "commands" / f"{name}.toml"] = _to_bytes(
            f"# .gemini/commands/{name}.toml\n"
            "# Where: generated Gemini CLI command adapter.\n"
            f"# What: Gemini command adapter for .agents/commands/{name}.md.\n"
            "# Why: Gemini CLI discovers custom commands as TOML files.\n"
            f"# {GENERATED_NOTE}\n\n"
            f"description = {_toml_basic_string(description)}\n"
            f"prompt = {_toml_multiline(gemini_prompt)}\n"
        )
    return outputs


def _skill_adapters(source_root: Path, output_root: Path) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    source_skills_root = source_root / ".agents" / "skills"
    for skill_md in sorted(source_skills_root.glob("*/SKILL.md")):
        skill_name = skill_md.parent.name
        outputs[output_root / ".claude" / "skills" / skill_name / "SKILL.md"] = (
            skill_md.read_bytes()
        )
    return outputs


def _mcp_adapters(source_root: Path, output_root: Path) -> dict[Path, bytes]:
    """Generate MCP server configs from the effective project .mcp.json."""
    source = _resolve_mcp_root(source_root, output_root) / ".mcp.json"
    if not source.exists():
        return {}
    data = json.loads(_read_text(source))
    servers = data.get("mcpServers", {})
    if not servers:
        return {}

    outputs: dict[Path, bytes] = {}

    # Cursor: type + url + headers
    cursor_servers = {}
    for name, config in servers.items():
        cfg: dict = {}
        if "type" in config:
            cfg["type"] = config["type"]
        if "url" in config:
            cfg["url"] = config["url"]
        if "headers" in config:
            cfg["headers"] = config["headers"]
        if cfg:
            cursor_servers[name] = cfg
    if cursor_servers:
        outputs[output_root / ".cursor" / "mcp.json"] = _to_bytes(
            json.dumps({"mcpServers": cursor_servers}, indent=2) + "\n"
        )
        outputs[output_root / ".vscode" / "mcp.json"] = _to_bytes(
            json.dumps(
                {
                    "servers": {
                        name: {
                            **({"url": cfg["url"]} if "url" in cfg else {}),
                            **({"type": cfg["type"]} if "type" in cfg else {}),
                            **(
                                {
                                    "headers": {
                                        key.lower(): value
                                        for key, value in cfg["headers"].items()
                                    }
                                }
                                if "headers" in cfg
                                else {}
                            ),
                        }
                        for name, cfg in cursor_servers.items()
                    }
                },
                indent=2,
            )
            + "\n"
        )

    # Gemini CLI: httpUrl + type + headers
    gemini_servers = {}
    for name, config in servers.items():
        cfg = {}
        server_type = config.get("type")
        if server_type:
            cfg["type"] = server_type
        if "url" in config:
            if server_type == "http":
                cfg["httpUrl"] = config["url"]
            else:
                cfg["url"] = config["url"]
        if "headers" in config:
            cfg["headers"] = dict(config["headers"])
        if cfg:
            gemini_servers[name] = cfg
    if gemini_servers:
        outputs[output_root / ".gemini" / "settings.json"] = _to_bytes(
            json.dumps({"mcpServers": gemini_servers}, indent=2) + "\n"
        )

    return outputs


def _project_skill_files(source_root: Path, output_root: Path) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    skills_root = source_root / ".agents" / "skills"
    if not skills_root.exists():
        return outputs

    for source in sorted(skills_root.rglob("*")):
        if source.is_dir():
            continue
        relative_path = source.relative_to(skills_root)
        outputs[output_root / ".agents" / "skills" / relative_path] = source.read_bytes()
        outputs[output_root / ".codex" / "skills" / relative_path] = source.read_bytes()
    return outputs


def _project_script_files(source_root: Path, output_root: Path) -> dict[Path, bytes]:
    script_path = source_root / "sync_agent_assets.py"
    if not script_path.exists():
        return {}
    return {output_root / "sync_agent_assets.py": script_path.read_bytes()}


def _merge_project_mcp(source_root: Path, output_root: Path) -> bytes | None:
    source = source_root / ".mcp.json"
    if not source.exists():
        return None

    source_data = json.loads(_read_text(source))
    output = output_root / ".mcp.json"
    if output.exists():
        merged = json.loads(_read_text(output))
    else:
        merged = {}

    merged["mcpServers"] = {
        **merged.get("mcpServers", {}),
        **source_data.get("mcpServers", {}),
    }
    return _to_bytes(json.dumps(merged, indent=2) + "\n")


def _merge_project_codex_config(source_root: Path, output_root: Path) -> tuple[bytes | None, str | None]:
    source = source_root / ".codex" / "config.toml"
    if not source.exists():
        return None, None

    source_text = _read_text(source).strip()
    output = output_root / ".codex" / "config.toml"
    if not output.exists():
        return _to_bytes(source_text + "\n"), None

    output_text = _read_text(output)
    source_data = tomllib.loads(source_text)
    output_data = tomllib.loads(output_text)
    source_kaggle = source_data.get("mcp_servers", {}).get("kaggle")
    output_kaggle = output_data.get("mcp_servers", {}).get("kaggle")

    if output_kaggle == source_kaggle:
        return _to_bytes(output_text), None
    if output_kaggle is None:
        merged_text = output_text.rstrip() + "\n\n" + source_text + "\n"
        return _to_bytes(merged_text), None
    return None, "Skipped .codex/config.toml because [mcp_servers.kaggle] already exists."


def install_project_files(
    source_root: Path,
    output_root: Path,
) -> tuple[list[Path], list[str]]:
    written: list[Path] = []
    notes: list[str] = []

    for path, content in _project_skill_files(source_root, output_root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_bytes() == content:
            continue
        path.write_bytes(content)
        written.append(path)

    for path, content in _project_script_files(source_root, output_root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_bytes() != content:
            notes.append(
                "Skipped sync_agent_assets.py because the destination already has local changes."
            )
            continue
        if path.exists() and path.read_bytes() == content:
            continue
        path.write_bytes(content)
        written.append(path)

    mcp_content = _merge_project_mcp(source_root, output_root)
    if mcp_content is not None:
        mcp_path = output_root / ".mcp.json"
        mcp_path.parent.mkdir(parents=True, exist_ok=True)
        if not mcp_path.exists() or mcp_path.read_bytes() != mcp_content:
            mcp_path.write_bytes(mcp_content)
            written.append(mcp_path)

    codex_content, codex_note = _merge_project_codex_config(source_root, output_root)
    if codex_note is not None:
        notes.append(codex_note)
    if codex_content is not None:
        codex_path = output_root / ".codex" / "config.toml"
        codex_path.parent.mkdir(parents=True, exist_ok=True)
        if not codex_path.exists() or codex_path.read_bytes() != codex_content:
            codex_path.write_bytes(codex_content)
            written.append(codex_path)

    return written, notes


def _resolve_output_root(source_root: Path, output_root: Path | None) -> Path:
    return source_root if output_root is None else output_root


def render_files(
    source_root: Path,
    output_root: Path | None = None,
    *,
    include_mcp: bool = False,
    skills_only: bool = False,
) -> dict[Path, bytes]:
    output_root = _resolve_output_root(source_root, output_root)
    outputs: dict[Path, bytes] = {}
    if not skills_only:
        outputs.update(_agent_instruction_adapters(source_root, output_root))
    outputs.update(_command_adapters(source_root, output_root))
    outputs.update(_skill_adapters(source_root, output_root))
    if include_mcp:
        outputs.update(_mcp_adapters(source_root, output_root))
    return outputs


def _generated_dynamic_files(root: Path) -> list[Path]:
    paths: set[Path] = set()
    for pattern in GENERATED_DYNAMIC_GLOBS:
        paths.update(root.glob(pattern))
    return sorted(paths)


def _stale_generated_files(root: Path, expected: dict[Path, bytes]) -> list[Path]:
    expected_paths = set(expected)
    return [
        path for path in _generated_dynamic_files(root) if path not in expected_paths
    ]


def _remove_empty_generated_parents(root: Path, path: Path) -> None:
    dynamic_roots = [root / relative_root for relative_root in GENERATED_DYNAMIC_ROOTS]
    for stop_at in dynamic_roots:
        if path == stop_at or not path.is_relative_to(stop_at):
            continue

        current = path
        while current != stop_at:
            try:
                current.rmdir()
            except OSError:
                break
            current = current.parent
        return


def write_files(
    source_root: Path,
    output_root: Path | None = None,
    *,
    prune: bool = False,
    include_mcp: bool = False,
    skills_only: bool = False,
) -> tuple[list[Path], list[Path]]:
    output_root = _resolve_output_root(source_root, output_root)
    written: list[Path] = []
    removed: list[Path] = []
    outputs = render_files(source_root, output_root, include_mcp=include_mcp, skills_only=skills_only)

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.read_bytes() == content:
            continue
        path.write_bytes(content)
        written.append(path)

    if prune:
        for path in _stale_generated_files(output_root, outputs):
            path.unlink()
            removed.append(path)
            _remove_empty_generated_parents(output_root, path.parent)

    return written, removed


def check_files(
    source_root: Path,
    output_root: Path | None = None,
    *,
    prune: bool = False,
    include_mcp: bool = False,
    skills_only: bool = False,
) -> list[Path]:
    output_root = _resolve_output_root(source_root, output_root)
    stale: list[Path] = []
    outputs = render_files(source_root, output_root, include_mcp=include_mcp, skills_only=skills_only)

    for path, content in outputs.items():
        if not path.exists() or path.read_bytes() != content:
            stale.append(path)
    if prune:
        stale.extend(_stale_generated_files(output_root, outputs))
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync generated AI-agent adapter files from .agents-source."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated files are stale.",
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="Include generated files whose shared sources no longer exist; remove them during sync.",
    )
    parser.add_argument(
        "--mcp",
        action="store_true",
        help="Include MCP server configs in sync. WARNING: May overwrite existing MCP settings.",
    )
    parser.add_argument(
        "--skills",
        action="store_true",
        help="Sync skills only; skip instruction adapters (CLAUDE.md, GEMINI.md, etc.).",
    )
    args = parser.parse_args()

    # Determine source and output roots
    cwd = Path.cwd()
    script_dir = Path(__file__).resolve().parent

    # If .agents-source exists in cwd, use it as source; otherwise use script_dir (self)
    if (cwd / ".agents-source").exists():
        source_root = cwd / ".agents-source"
        output_root = cwd
    else:
        source_root = script_dir
        output_root = script_dir

    if args.check:
        stale = check_files(source_root, output_root, prune=args.prune, include_mcp=args.mcp, skills_only=args.skills)
        if stale:
            print("Stale generated agent files:")
            for path in stale:
                print(path.relative_to(output_root))
            return 1
        print("Generated agent files are up to date.")
        return 0

    installed: list[Path] = []
    notes: list[str] = []
    if source_root != output_root:
        installed, notes = install_project_files(source_root, output_root)

    written, removed = write_files(source_root, output_root, prune=args.prune, include_mcp=args.mcp, skills_only=args.skills)
    if not installed and not written and not removed and not notes:
        print("Generated agent files are already up to date.")
        return 0
    if installed:
        print("Installed project files:")
        for path in installed:
            print(path.relative_to(output_root))
    if written:
        print("Updated generated agent files:")
        for path in written:
            print(path.relative_to(output_root))
    if removed:
        print("Removed stale generated agent files:")
        for path in removed:
            print(path.relative_to(output_root))
    if notes:
        print("Notes:")
        for note in notes:
            print(note)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
